<a href="https://colab.research.google.com/github/lhpinheiro09/lhpinheiro09/blob/main/ClassificacaoDesafio.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **SUPERVISED LEARNING: CLASSIFICATION**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


This project aims to develop a Machine Learning algorithm for predict whether the cancer is benign or malignant.




The data were extracted from the Kaggle website:
https://www.kaggle.com/datasets/uciml/breast-cancer-wisconsin-data?resource=download

## **PRE-PROCESSING**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Cursos Udemy/Machine Learning com Python/BCWDiagnostic_treated.csv', sep=',', encoding='utf-8')

In [ ]:
df.head(20)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0     842302         M        17.99         10.38          122.80     1001.0   
1     842517         M        20.57         17.77          132.90     1326.0   
2   84300903         M        19.69         21.25          130.00     1203.0   
3   84348301         M        11.42         20.38           77.58      386.1   
4   84358402         M        20.29         14.34          135.10     1297.0   
5     843786         M        12.45         15.70           82.57      477.1   
6     844359         M        18.25         19.98          119.60     1040.0   
7   84458202         M        13.71         20.83           90.20      577.9   
8     844981         M        13.00         21.82           87.50      519.8   
9   84501001         M        12.46         24.04           83.97      475.9   
10    845636         M        16.02         23.24          102.70      797.8   
11  84610002         M        15.78         17.89          103.60      781.0   
12    846226         M        19.17         24.80          132.40     1123.0   
13    846381         M        15.85         23.95          103.70      782.7   
14  84667401         M        13.73         22.61           93.60      578.3   
15  84799002         M        14.54         27.54           96.73      658.8   
16    848406         M        14.68         20.13           94.74      684.5   
17  84862001         M        16.13         20.68          108.10      798.8   
18    849014         M        19.81         22.15          130.00     1260.0   
19   8510426         B        13.54         14.36           87.46      566.3   

    smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0           0.11840           0.27760         0.30010              0.14710   
1           0.08474           0.07864         0.08690              0.07017   
2           0.10960           0.15990         0.19740              0.12790   
3           0.14250           0.28390         0.24140              0.10520   
4           0.10030           0.13280         0.19800              0.10430   
5           0.12780           0.17000         0.15780              0.08089   
6           0.09463           0.10900         0.11270              0.07400   
7           0.11890           0.16450         0.09366              0.05985   
8           0.12730           0.19320         0.18590              0.09353   
9           0.11860           0.23960         0.22730              0.08543   
10          0.08206           0.06669         0.03299              0.03323   
11          0.09710           0.12920         0.09954              0.06606   
12          0.09740           0.24580         0.20650              0.11180   
13          0.08401           0.10020         0.09938              0.05364   
14          0.11310           0.22930         0.21280              0.08025   
15          0.11390           0.15950         0.16390              0.07364   
16          0.09867           0.07200         0.07395              0.05259   
17          0.11700           0.20220         0.17220              0.10280   
18          0.09831           0.10270         0.14790              0.09498   
19          0.09779           0.08129         0.06664              0.04781   

    ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0   ...         25.38          17.33           184.60      2019.0   
1   ...         24.99          23.41           158.80      1956.0   
2   ...         23.57          25.53           152.50      1709.0   
3   ...         14.91          26.50            98.87       567.7   
4   ...         22.54          16.67           152.20      1575.0   
5   ...         15.47          23.75           103.40       741.6   
6   ...         22.88          27.66           153.20      1606.0   
7   ...         17.06          28.14           110.60       897.0   
8   ...         15.49          30.73           106.20       739.3   


In [ ]:
df.shape

(569, 32)

In [ ]:
df.dtypes

id                           int64
diagnosis                   object
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
smoothness_worst           float64
compactness_worst          float64
concavity_worst     

# **Transforming nominal categorical variables into ordinal categorical variables**

In [ ]:
df2 = pd.DataFrame.copy(df)

In [ ]:
df2['diagnosis'].replace({'B':0, 'M':1}, inplace=True)

In [ ]:
df2.head(20)

id  diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0     842302          1        17.99         10.38          122.80     1001.0   
1     842517          1        20.57         17.77          132.90     1326.0   
2   84300903          1        19.69         21.25          130.00     1203.0   
3   84348301          1        11.42         20.38           77.58      386.1   
4   84358402          1        20.29         14.34          135.10     1297.0   
5     843786          1        12.45         15.70           82.57      477.1   
6     844359          1        18.25         19.98          119.60     1040.0   
7   84458202          1        13.71         20.83           90.20      577.9   
8     844981          1        13.00         21.82           87.50      519.8   
9   84501001          1        12.46         24.04           83.97      475.9   
10    845636          1        16.02         23.24          102.70      797.8   
11  84610002          1        15.78         17.89          103.60      781.0   
12    846226          1        19.17         24.80          132.40     1123.0   
13    846381          1        15.85         23.95          103.70      782.7   
14  84667401          1        13.73         22.61           93.60      578.3   
15  84799002          1        14.54         27.54           96.73      658.8   
16    848406          1        14.68         20.13           94.74      684.5   
17  84862001          1        16.13         20.68          108.10      798.8   
18    849014          1        19.81         22.15          130.00     1260.0   
19   8510426          0        13.54         14.36           87.46      566.3   

    smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0           0.11840           0.27760         0.30010              0.14710   
1           0.08474           0.07864         0.08690              0.07017   
2           0.10960           0.15990         0.19740              0.12790   
3           0.14250           0.28390         0.24140              0.10520   
4           0.10030           0.13280         0.19800              0.10430   
5           0.12780           0.17000         0.15780              0.08089   
6           0.09463           0.10900         0.11270              0.07400   
7           0.11890           0.16450         0.09366              0.05985   
8           0.12730           0.19320         0.18590              0.09353   
9           0.11860           0.23960         0.22730              0.08543   
10          0.08206           0.06669         0.03299              0.03323   
11          0.09710           0.12920         0.09954              0.06606   
12          0.09740           0.24580         0.20650              0.11180   
13          0.08401           0.10020         0.09938              0.05364   
14          0.11310           0.22930         0.21280              0.08025   
15          0.11390           0.15950         0.16390              0.07364   
16          0.09867           0.07200         0.07395              0.05259   
17          0.11700           0.20220         0.17220              0.10280   
18          0.09831           0.10270         0.14790              0.09498   
19          0.09779           0.08129         0.06664              0.04781   

    ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0   ...         25.38          17.33           184.60      2019.0   
1   ...         24.99          23.41           158.80      1956.0   
2   ...         23.57          25.53           152.50      1709.0   
3   ...         14.91          26.50            98.87       567.7   
4   ...         22.54          16.67           152.20      1575.0   
5   ...         15.47          23.75           103.40       741.6   
6   ...         22.88          27.66           153.20      1606.0   
7   ...         17.06          28.14           110.60       897.0   
8   ...         15.49          30.73           1

In [ ]:
df2.dtypes

id                           int64
diagnosis                    int64
radius_mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
smoothness_worst           float64
compactness_worst          float64
concavity_worst     

In [ ]:
df2.shape

(569, 32)

# **Subtitle**

id = ID number

diagnosis = The diagnosis of breast tissues (M = malignant, B = benign)

radius_mean = mean of distances from center to points on the perimeter

texture_mean = standard deviation of gray-scale values

perimeter_mean = mean size of the core tumor

area_mean =

smoothness_mean = mean of local variation in radius lengths

compactness_mean = mean of perimeter^2 / area - 1.0

concavity_mean = mean of severity of concave portions of the contour

concave points_mean = mean for number of concave portions of the contour

symmetry_mean =

fractal_dimension_mean = mean for "coastline approximation" - 1

radius_se = standard error for the mean of distances from center to points on the perimeter

texture_se = standard error for standard deviation of gray-scale values

perimeter_se =

area_se =

smoothness_se = standard error for local variation in radius lengths

compactness_se = standard error for perimeter^2 / area - 1.0

concavity_se = standard error for severity of concave portions of the contour

concave points_se = standard error for number of concave portions of the contour

symmetry_se =

fractal_dimension_se = standard error for "coastline approximation" - 1

radius_worst = "worst" or largest mean value for mean of distances from center to points on the perimeter

texture_worst = "worst" or largest mean value for standard deviation of gray-scale values

perimeter_worst =

area_worst =

smoothness_worst = "worst" or largest mean value for local variation in radius lengths

compactness_worst = "worst" or largest mean value for perimeter^2 / area - 1.0

concavity_worst = "worst" or largest mean value for severity of concave portions of the contour

concave points_worst = "worst" or largest mean value for number of concave portions of the contour

symmetry_worst =

fractal_dimension_worst = "worst" or largest mean value for "coastline approximation" - 1

## Predictor and Target Attributes

In [ ]:
df2.head()

id  diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302          1        17.99         10.38          122.80     1001.0   
1    842517          1        20.57         17.77          132.90     1326.0   
2  84300903          1        19.69         21.25          130.00     1203.0   
3  84348301          1        11.42         20.38           77.58      386.1   
4  84358402          1        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [ ]:
previsores = df2.iloc[:, 2:33].values

In [ ]:
previsores

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [ ]:
previsores.shape

(569, 30)

In [ ]:
alvo = df2.iloc[:, 1].values

In [ ]:
alvo

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [ ]:
alvo.shape

(569,)

In [ ]:
df2.describe()

id   diagnosis  radius_mean  texture_mean  perimeter_mean  \
count  5.690000e+02  569.000000   569.000000    569.000000      569.000000   
mean   3.037183e+07    0.372583    14.127292     19.289649       91.969033   
std    1.250206e+08    0.483918     3.524049      4.301036       24.298981   
min    8.670000e+03    0.000000     6.981000      9.710000       43.790000   
25%    8.692180e+05    0.000000    11.700000     16.170000       75.170000   
50%    9.060240e+05    0.000000    13.370000     18.840000       86.240000   
75%    8.813129e+06    1.000000    15.780000     21.800000      104.100000   
max    9.113205e+08    1.000000    28.110000     39.280000      188.500000   

         area_mean  smoothness_mean  compactness_mean  concavity_mean  \
count   569.000000       569.000000        569.000000      569.000000   
mean    654.889104         0.096360          0.104341        0.088799   
std     351.914129         0.014064          0.052813        0.079720   
min     143.500000         0.052630          0.019380        0.000000   
25%     420.300000         0.086370          0.064920        0.029560   
50%     551.100000         0.095870          0.092630        0.061540   
75%     782.700000         0.105300          0.130400        0.130700   
max    2501.000000         0.163400          0.345400        0.426800   

       concave points_mean  ...  radius_worst  texture_worst  perimeter_worst  \
count           569.000000  ...    569.000000     569.000000       569.000000   
mean              0.048919  ...     16.269190      25.677223       107.261213   
std               0.038803  ...      4.833242       6.146258        33.602542   
min               0.000000  ...      7.930000      12.020000        50.410000   
25%               0.020310  ...     13.010000      21.080000        84.110000   
50%               0.033500  ...     14.970000      25.410000        97.660000   
75%               0.074000  ...     18.790000      29.720000       125.400000   
max               0.201200  ...     36.040000      49.540000       251.200000   

        area_worst  smoothness_worst  compactness_worst  concavity_worst  \
count   569.000000        569.000000         569.000000       569.000000   
mean    880.583128          0.132369           0.254265         0.272188   
std     569.356993          0.022832           0.157336         0.208624   
min     185.200000          0.071170           0.027290         0.000000   
25%     515.300000          0.116600           0.147200         0.114500   
50%     686.500000          0.131300           0.211900         0.226700   
75%    1084.000000          0.146000           0.339100         0.382900   
max    4254.000000          0.222600           1.058000         1.252000   

       concave points_worst  symmetry_worst  fractal_dimension_worst  
count            569.000000      569.000000               569.000000  
mean               0.114606        0.290076                 0.083946  
std                0.065732        0.061867                 0.018061  
min                0.000000        0.156500                 0.055040  
25%                0.064930        0.250400                 0.071460  
50%                0.099930        0.282200                 0.080040  
75%                0.161400        0.317900                 0.092080  
max                0.291000        0.663800                 0.207500  

[8 rows x 32 columns]

In [ ]:
df2.head().T

0              1             2  \
id                       842302.000000  842517.000000  8.430090e+07   
diagnosis                     1.000000       1.000000  1.000000e+00   
radius_mean                  17.990000      20.570000  1.969000e+01   
texture_mean                 10.380000      17.770000  2.125000e+01   
perimeter_mean              122.800000     132.900000  1.300000e+02   
area_mean                  1001.000000    1326.000000  1.203000e+03   
smoothness_mean               0.118400       0.084740  1.096000e-01   
compactness_mean              0.277600       0.078640  1.599000e-01   
concavity_mean                0.300100       0.086900  1.974000e-01   
concave points_mean           0.147100       0.070170  1.279000e-01   
symmetry_mean                 0.241900       0.181200  2.069000e-01   
fractal_dimension_mean        0.078710       0.056670  5.999000e-02   
radius_se                     1.095000       0.543500  7.456000e-01   
texture_se                    0.905300       0.733900  7.869000e-01   
perimeter_se                  8.589000       3.398000  4.585000e+00   
area_se                     153.400000      74.080000  9.403000e+01   
smoothness_se                 0.006399       0.005225  6.150000e-03   
compactness_se                0.049040       0.013080  4.006000e-02   
concavity_se                  0.053730       0.018600  3.832000e-02   
concave points_se             0.015870       0.013400  2.058000e-02   
symmetry_se                   0.030030       0.013890  2.250000e-02   
fractal_dimension_se          0.006193       0.003532  4.571000e-03   
radius_worst                 25.380000      24.990000  2.357000e+01   
texture_worst                17.330000      23.410000  2.553000e+01   
perimeter_worst             184.600000     158.800000  1.525000e+02   
area_worst                 2019.000000    1956.000000  1.709000e+03   
smoothness_worst              0.162200       0.123800  1.444000e-01   
compactness_worst             0.665600       0.186600  4.245000e-01   
concavity_worst               0.711900       0.241600  4.504000e-01   
concave points_worst          0.265400       0.186000  2.430000e-01   
symmetry_worst                0.460100       0.275000  3.613000e-01   
fractal_dimension_worst       0.118900       0.089020  8.758000e-02   

                                    3             4  
id                       8.434830e+07  8.435840e+07  
diagnosis                1.000000e+00  1.000000e+00  
radius_mean              1.142000e+01  2.029000e+01  
texture_mean             2.038000e+01  1.434000e+01  
perimeter_mean           7.758000e+01  1.351000e+02  
area_mean                3.861000e+02  1.297000e+03  
smoothness_mean          1.425000e-01  1.003000e-01  
compactness_mean         2.839000e-01  1.328000e-01  
concavity_mean           2.414000e-01  1.980000e-01  
concave points_mean      1.052000e-01  1.043000e-01  
symmetry_mean            2.597000e-01  1.809000e-01  
fractal_dimension_mean   9.744000e-02  5.883000e-02  
radius_se                4.956000e-01  7.572000e-01  
texture_se               1.156000e+00  7.813000e-01  
perimeter_se             3.445000e+00  5.438000e+00  
area_se                  2.723000e+01  9.444000e+01  
smoothness_se            9.110000e-03  1.149000e-02  
compactness_se           7.458000e-02  2.461000e-02  
concavity_se             5.661000e-02  5.688000e-02  
concave points_se        1.867000e-02  1.885000e-02  
symmetry_se              5.963000e-02  1.756000e-02  
fractal_dimension_se     9.208000e-03  5.115000e-03  
radius_worst             1.491000e+01  2.254000e+01  
texture_worst            2.650000e+01  1.667000e+01  
perimeter_worst          9.887000e+01  1.522000e+02  
area_worst               5.677000e+02  1.575000e+03  
smoothness_worst         2.098000e-01  1.374000e-01  
compactness_worst        8.663000e-01  2.050000e-01  
concavity_worst          6.869000e-01  4.000000e-01  
concave points_worst     2.575000e-01  1.625000e-01  
symmetry_worst     

## Dimensionality reduction

Objective is to select the best components (attributes) for algorithm training by analyzing the correlations between the variables.

In [ ]:
from sklearn.decomposition import PCA

In [ ]:
pca = PCA(n_components=10)

In [ ]:
previsores_pca = pca.fit_transform(previsores)

In [ ]:
previsores_pca.shape

(569, 10)

In [ ]:
# componentes principais
previsores_pca

array([[ 1.16014257e+03, -2.93917544e+02,  4.85783976e+01, ...,
         1.48167035e-01,  7.45463100e-01,  5.89359489e-01],
       [ 1.26912244e+03,  1.56301818e+01, -3.53945342e+01, ...,
         2.00803920e-01, -4.85827948e-01, -8.40347188e-02],
       [ 9.95793889e+02,  3.91567432e+01, -1.70975298e+00, ...,
        -2.74025583e-01, -1.73874273e-01, -1.86993508e-01],
       ...,
       [ 3.14501756e+02,  4.75535252e+01, -1.04424072e+01, ...,
        -4.42278787e-01, -9.73984733e-02, -1.44667285e-01],
       [ 1.12485812e+03,  3.41292250e+01, -1.97420874e+01, ...,
        -3.59964104e-01,  3.85030186e-01,  6.15467490e-01],
       [-7.71527622e+02, -8.86431064e+01,  2.38890319e+01, ...,
         3.00390899e-02, -4.23451051e-01, -3.01438975e-01]])

In [ ]:
# razão das variáveis explicativas
pca.explained_variance_ratio_

array([9.82044672e-01, 1.61764899e-02, 1.55751075e-03, 1.20931964e-04,
       8.82724536e-05, 6.64883951e-06, 4.01713682e-06, 8.22017197e-07,
       3.44135279e-07, 1.86018721e-07])

In [ ]:
# soma das variáveis explicativas
pca.explained_variance_ratio_.sum()

0.9999998946838412

## Training and Testing Base

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_treino, x_teste, y_treino, y_teste = train_test_split(previsores, alvo, test_size = 0.3, random_state = 0)

In [ ]:
x_treino.shape

(398, 30)

In [ ]:
x_teste.shape

(171, 30)

In [ ]:
y_treino.shape

(398,)

In [ ]:
y_teste.shape

(171,)

## RANDOM FOREST

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
random = RandomForestClassifier(n_estimators=150, criterion='entropy', random_state = 0, max_depth=4)
random.fit(x_treino, y_treino)

RandomForestClassifier(criterion='entropy', max_depth=4, n_estimators=150,
                       random_state=0)

In [ ]:
previsoes_random = random.predict(x_teste)
previsoes_random

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0])

In [ ]:
y_teste

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0])

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_random) * 100.0))

Acurácia: 96.49%


In [ ]:
confusion_matrix(y_teste, previsoes_random)

array([[106,   2],
       [  4,  59]])

In [ ]:
print(classification_report(y_teste, previsoes_random))

              precision    recall  f1-score   support

           0       0.96      0.98      0.97       108
           1       0.97      0.94      0.95        63

    accuracy                           0.96       171
   macro avg       0.97      0.96      0.96       171
weighted avg       0.96      0.96      0.96       171



**Analysis of training data**

In [ ]:
previsoes_treino = random.predict(x_treino)
previsoes_treino

array([0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,

In [ ]:
accuracy_score(y_treino, previsoes_treino)

0.9899497487437185

In [ ]:
confusion_matrix(y_treino, previsoes_treino)

array([[249,   0],
       [  4, 145]])

**Cross-validation**

In [ ]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [ ]:
# Separando os dados em folds
kfold = KFold(n_splits = 30, shuffle=True, random_state = 5)

In [ ]:
# Criando o modelo
modelo = RandomForestClassifier(n_estimators=150, criterion='entropy', random_state = 0, max_depth=4)
resultado = cross_val_score(modelo, previsores, alvo, cv = kfold)

In [ ]:
# Usamos a média e o desvio padrão
print("Acurácia Média: %.2f%%" % (resultado.mean() * 100.0))

Acurácia Média: 95.76%
